### ISSUE TITLE
CosmoMC ini templates

### ISSUE THREAD

**Issue by maria-vincenzi** [Samreay/Pippin#5]
Hello, 
I have an issue with adding new cosmomc .ini templates.
I added at the top ok my script the lines:
```
GLOBAL:
  DATA_DIRS:
    - /path/to/my/own/ini
```
and in the section CREATE_COV and COSMOMC I have:

```
CREATE_COV:
  ALL:
    OPTS:
      COVOPTS:
	- "[NOSYS] [=DEFAULT,=DEFAULT]"

COSMOMC:
  SN_CMB_OMW:
    OPTS:
      INI: my_own_ini
      COVOPTS: [ALL, NOSYS]

```
However this is not working. I think the problem is that all the .ini files are created at the step CREATE_COV. They are built from the templates available in `data_files/cosmomc_templates`  and they are stored in the `output` folder in `7_CREATE_COV`. At this stage the code doesn't know that there's an extra cosmomc template in my own folder. At step 8, I specified that I want the .ini file my_own_ini. However pippin cannot find in 7_CREATE_COV the .ini file matching the string `my_own_ini`.
Is there a way to get around this?
Thanks!!
